//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nameless.Libraries.Rukia.ProjectEuler.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nameless.Libraries.Rukia.ProjectEuler.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;MARY&quot;,&quot;PATRICIA&quot;,&quot;LINDA&quot;,&quot;BARBARA&quot;,&quot;ELIZABETH&quot;,&quot;JENNIFER&quot;,&quot;MARIA&quot;,&quot;SUSAN&quot;,&quot;MARGARET&quot;,&quot;DOROTHY&quot;,&quot;LISA&quot;,&quot;NANCY&quot;,&quot;KAREN&quot;,&quot;BETTY&quot;,&quot;HELEN&quot;,&quot;SANDRA&quot;,&quot;DONNA&quot;,&quot;CAROL&quot;,&quot;RUTH&quot;,&quot;SHARON&quot;,&quot;MICHELLE&quot;,&quot;LAURA&quot;,&quot;SARAH&quot;,&quot;KIMBERLY&quot;,&quot;DEBORAH&quot;,&quot;JESSICA&quot;,&quot;SHIRLEY&quot;,&quot;CYNTHIA&quot;,&quot;ANGELA&quot;,&quot;MELISSA&quot;,&quot;BRENDA&quot;,&quot;AMY&quot;,&quot;ANNA&quot;,&quot;REBECCA&quot;,&quot;VIRGINIA&quot;,&quot;KATHLEEN&quot;,&quot;PAMELA&quot;,&quot;MARTHA&quot;,&quot;DEBRA&quot;,&quot;AMANDA&quot;,&quot;STEPHANIE&quot;,&quot;CAROLYN&quot;,&quot;CHRISTINE&quot;,&quot;MARIE&quot;,&quot;JANET&quot;,&quot;CATHERINE&quot;,&quot;FRANCES&quot;,&quot;ANN&quot;,&quot;JOYCE&quot;,&quot;DIANE&quot;,&quot;ALICE&quot;,&quot;JULIE&quot;,&quot;HEATHER&quot;,&quot;TER....
        /// </summary>
        internal static string p022_names {
            get {
                return ResourceManager.GetString("p022_names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;A&quot;,&quot;ABILITY&quot;,&quot;ABLE&quot;,&quot;ABOUT&quot;,&quot;ABOVE&quot;,&quot;ABSENCE&quot;,&quot;ABSOLUTELY&quot;,&quot;ACADEMIC&quot;,&quot;ACCEPT&quot;,&quot;ACCESS&quot;,&quot;ACCIDENT&quot;,&quot;ACCOMPANY&quot;,&quot;ACCORDING&quot;,&quot;ACCOUNT&quot;,&quot;ACHIEVE&quot;,&quot;ACHIEVEMENT&quot;,&quot;ACID&quot;,&quot;ACQUIRE&quot;,&quot;ACROSS&quot;,&quot;ACT&quot;,&quot;ACTION&quot;,&quot;ACTIVE&quot;,&quot;ACTIVITY&quot;,&quot;ACTUAL&quot;,&quot;ACTUALLY&quot;,&quot;ADD&quot;,&quot;ADDITION&quot;,&quot;ADDITIONAL&quot;,&quot;ADDRESS&quot;,&quot;ADMINISTRATION&quot;,&quot;ADMIT&quot;,&quot;ADOPT&quot;,&quot;ADULT&quot;,&quot;ADVANCE&quot;,&quot;ADVANTAGE&quot;,&quot;ADVICE&quot;,&quot;ADVISE&quot;,&quot;AFFAIR&quot;,&quot;AFFECT&quot;,&quot;AFFORD&quot;,&quot;AFRAID&quot;,&quot;AFTER&quot;,&quot;AFTERNOON&quot;,&quot;AFTERWARDS&quot;,&quot;AGAIN&quot;,&quot;AGAINST&quot;,&quot;AGE&quot;,&quot;AGENCY&quot;,&quot;AGENT&quot;,&quot;AGO&quot;,&quot;AGREE&quot;,&quot;AGREEMENT&quot;,&quot....
        /// </summary>
        internal static string p042_words {
            get {
                return ResourceManager.GetString("p042_words", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8C TS KC 9H 4S 7D 2S 5D 3S AC
        ///5C AD 5D AC 9C 7C 5H 8D TD KS
        ///3H 7H 6S KC JS QH TD JC 2D 8S
        ///TH 8H 5C QS TC 9H 4D JC KS JS
        ///7C 5H KC QH JD AS KH 4C AD 4S
        ///5H KS 9C 7D 9H 8D 3S 5D 5C AH
        ///6H 4H 5C 3H 2H 3S QH 5S 6S AS
        ///TD 8C 4H 7C TC KC 4C 3H 7S KS
        ///7C 9C 6D KD 3H 4C QS QC AC KH
        ///JC 6S 5H 2H 2D KD 9D 7C AS JS
        ///AD QH TH 9D 8H TS 6D 3S AS AC
        ///2H 4S 5C 5S TC KC JD 6C TS 3C
        ///QD AS 6H JS 2C 3D 9H KC 4H 8S
        ///KD 8S 9S 7C 2S 3S 6D 6S 4H KC
        ///3C 8C 2D 7D 4D 9S 4S QH 4H JD
        ///8C KC 7S TC 2D TS 8H QD AC 5C
        ///3D KH QD 6C 6S AD AS 8H 2H QS
        ///6S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string p054_poker {
            get {
                return ResourceManager.GetString("p054_poker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 79,59,12,2,79,35,8,28,20,2,3,68,8,9,68,45,0,12,9,67,68,4,7,5,23,27,1,21,79,85,78,79,85,71,38,10,71,27,12,2,79,6,2,8,13,9,1,13,9,8,68,19,7,1,71,56,11,21,11,68,6,3,22,2,14,0,30,79,1,31,6,23,19,10,0,73,79,44,2,79,19,6,28,68,16,6,16,15,79,35,8,11,72,71,14,10,3,79,12,2,79,19,6,28,68,32,0,0,73,79,86,71,39,1,71,24,5,20,79,13,9,79,16,15,10,68,5,10,3,14,1,10,14,1,3,71,24,13,19,7,68,32,0,0,73,79,87,71,39,1,71,12,22,2,14,16,2,11,68,2,25,1,21,22,16,15,6,10,0,79,16,15,10,22,2,79,13,20,65,68,41,0,16,15,6,10,0,79,1,31,6,2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string p059_cipher {
            get {
                return ResourceManager.GetString("p059_cipher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 59
        ///73 41
        ///52 40 09
        ///26 53 06 34
        ///10 51 87 86 81
        ///61 95 66 57 25 68
        ///90 81 80 38 92 67 73
        ///30 28 51 76 81 18 75 44
        ///84 14 95 87 62 81 17 78 58
        ///21 46 71 58 02 79 62 39 31 09
        ///56 34 35 53 78 31 81 18 90 93 15
        ///78 53 04 21 84 93 32 13 97 11 37 51
        ///45 03 81 79 05 18 78 86 13 30 63 99 95
        ///39 87 96 28 03 38 42 17 82 87 58 07 22 57
        ///06 17 51 17 07 93 09 07 75 97 95 78 87 08 53
        ///67 66 59 60 88 99 94 65 55 77 55 34 27 53 78 28
        ///76 40 41 04 87 16 09 42 75 69 23 97 30 60 10 79 87
        ///12 10 44 26 21 36 32 84 98 60 13 12  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pyramid2 {
            get {
                return ResourceManager.GetString("pyramid2", resourceCulture);
            }
        }
    }
}
